# Site settings
email:
baseurl: ""
paginate: 10
paginate_path: "/page-:num"
google_analytics:
highlighter: pygments

# SEO settings
title: Vitor Meriat
description:
url: ""
twitter_username:
default_img:

# Profile settings
name:
profile_img:
profile:
social:
  github:

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
